### ISSUE TITLE
Debug Log Check

### ISSUE THREAD

**Issue by MjnMixael** [ngld/old-knossos#104]
It's pretty easy to upload an unrelated debug log. I've seen in the past on the forums where users upload a log that lists the wrong mod based on what they wanted support on. So I'm thinking the same may crop up here where I suspect they forgot to actually run debug recently and uploaded an old log.

Could we do a simple check "If Debug Log older than X amount of time" then we display a small warning when the user selects Upload Debug Log "Your Debug Log looks pretty old. Are you sure you want to upload this one? If not, simply run FSO Debug again to make sure a new log is created."

Or something.

**Comment by ngld** [comment]
This has been implemented as of 0.7.2.
