### ISSUE TITLE
Leaving Windows 10 locked while downloading a mod causes a partial freeze

### ISSUE THREAD

**Issue by plieblang** [ngld/old-knossos#115]
Steps to repro:  Start downloading a large mod; lock Windows 10 and leave it locked for a while (not sure of the exact time needed); sign back in; observe the following problem.
The whole UI is frozen until I resize the window.  Then everything works properly except the download has frozen.  Cancelling it freezes Knossos permanently.

**Comment by ngld** [comment]
I haven't been able to reproduce this. Is this still a problem?

**Comment by plieblang** [comment]
No, it doesn't look like it is.
