### ISSUE TITLE
Deleting local files after deleting a mod version doesn't work

### ISSUE THREAD

**Issue by plieblang** [ngld/old-knossos#117]
Deleting a mod version and then clicking yes on the popup asking to delete the local files doesn't result in the local files being deleted.  This happens whether or not the mod version is deleted from the Nebula.

**Comment by ngld** [comment]
Knossos only tries to delete the files it knows about which works well with mods that were installed through Knossos but obviously fails for dev mods. This will be fixed in the next version.
