### ISSUE TITLE
Can't Build 0.9.4 on Ubuntu 18.04

### ISSUE THREAD

**Issue by GlacialTurtle** [ngld/old-knossos#124]
Trying to build on 18.04 but it doesn't seem to find ply (it is definitely installed). Error message from running `python3 configure.py`

> File "configure.py", line 103, in <module>
    pylupdate = try_program([[sys.executable, '-mPyQt5.pylupdate_main'], ['pylupdate5'], ['pylupdate']], 'pylupdate', test_param='-version')
  File "/home/ryan/Other/knossos-0.9.4/tools/common/configlib.py", line 212, in try_program
    silent_check(cmd + [test_param])
  File "/home/ryan/Other/knossos-0.9.4/tools/common/configlib.py", line 34, in silent_check
    return check_call(*args, **kwargs)
  File "/usr/lib/python3.6/subprocess.py", line 286, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/usr/lib/python3.6/subprocess.py", line 267, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'pylupdate5': 'pylupdate5'

**Comment by ngld** [comment]
`pylupdate5` is part of PyQt5 and unrelated to ply.

**Comment by GlacialTurtle** [comment]
Definitely have that installed too, still doesn't work.

**Comment by ngld** [comment]
Do you have `pyqt5-dev-tools`? It's probably in there. If it still doesn't work, make sure you can run `pylupdate5` on your shell.

**Comment by GlacialTurtle** [comment]
It was pyqt5-dev-tools missing, thank you! Also had to install libqt4-dev for it to actually run with `ninja run` and it now works.

**Comment by ngld** [comment]
Great! I'm glad it worked for you.
