### ISSUE TITLE
PPA dependencies incomplete

### ISSUE THREAD

**Issue by niffiwan** [ngld/old-knossos#14]
On Mint 17 using the PPA, I needed to install all the recommend packages in order for knossos to run correctly.  i.e.

$ sudo apt-get install knossos
Reading package lists... Done
Building dependency tree  
Reading state information... Done
The following extra packages will be installed:
  libsdl2-2.0-0 p7zip-full python3-semantic-version
Suggested packages:
  p7zip-rar
Recommended packages:
  python3-pyside.qtgui python3-pyside.qtnetwork python3-pyside.qtwebkit
The following NEW packages will be installed:
  knossos libsdl2-2.0-0 p7zip-full python3-semantic-version
(etc)

Then

sudo apt-get install python3-pyside.qtgui python3-pyside.qtnetwork python3-pyside.qtwebkit

I'd thought that if these are required to run then it should pull them all in automatically?

**Comment by ngld** [comment]
Knossos works with PyQt4 and PySide, I wanted to leave the choice to the user.
If you already have PyQt4 installed, you don't need PySide. I'll see if I can actually declare this as a dependency.

**Comment by niffiwan** [comment]
Sorry! User error; I had python-qt4 installed, not python3-qt4... so it probably doesn't need fixing.

**Comment by ngld** [comment]
I'll add the PySide packages as dependencies in the next release. PyQt4 causes a bug I'd like to avoid.
I'm going to leave this issue open as a reminder until I've finished the next release.

**Comment by ngld** [comment]
The 0.1.0 package has been released a while ago, I guess I can close this.
