### ISSUE TITLE
Is fsnebula.org/knossos/ down?

### ISSUE THREAD

**Issue by Mestake** [ngld/old-knossos#144]
It gives me "504 Gateway Time-out", no matter if I try with my Russian IP or if I behind US/German/Canada proxy.

**Comment by ngld** [comment]
Should be back up now. The server process got stuck. Not (yet) sure why that happened.

**Comment by Mestake** [comment]
I think there  should be more download options, like github-releases, google drive, sourceforge, and so on; so people could install knossos even fsnebula is down. For now you completely depend on one download place which is not good.

**Comment by ngld** [comment]
The download links on fsnebula.org just redirect to the latest GitHub release. You'll see that all downloads (even previous releases) are there.

Besides if fsnebula.org is down, mod downloads don't work so even if you can install Knossos, it'd be kind of useless.
