### ISSUE TITLE
Update the mod list using delta updates whenever possible

### ISSUE THREAD

**Issue by jg18** [ngld/old-knossos#154]
I did some performance experiments to understand why there's a 2-second delay when switching to the Explore tab and learned a couple things:
- The JSON dumping/serializing (Python) and parsing (JS) operations are both very expensive.
- The JSON string passed when updating the Explore tab is 8 MB long (!)

This delay will be especially problematic once the sorting menu is implemented. A full mod list update every time the sort type is changed would lead to a noticeable delay with every sort type change.

Thus I think  we should minimize the amount of data passed from Python to JS when updating the mod list.

One possible solution:
Maintain in both Python and JS mappings from mod ID to mod "record" where a record is the data that gets passed from Python to JS on a mod list update. The mapping would be a Python dict/JS obj and there would be two maps: one for all mods and one for installed mods, analogous to but separate from `center.mods` and `center.installed`.

After Knossos starts up, the Python code sends a full mod list update to JS  (the same code path currently used) for both all mods and for installed mods. 

Then in subsequent mod list updates, the Python code would send a JSON obj with three fields:
1. ~~`mod_list_type`: a string or other value indicating whether the update is for all mods or for installed ones~~ EDIT: this field is not needed because the JS knows which map to update based on which tab is visible (all mods if Explore, installed mods if Home/Develop)
2. `updated_mods` a Python dict/JS Object mapping mod IDs to mod records for mods that are to be displayed in this update and that have changed since the last mod list update for that mod list type 
3. `mod_order` a Python list/JS array of mod IDs that indicates which mods should be displayed and in what order they should be displayed

As a first pass for implementing the delta, we can serialize a mod's entire record if any part of the mod's record has changed. If performance is still unsatisfactory (that is, if the JSON strings are still too big) then we can look into finer-grained deltas like only sending the fields that have changed. Since that approach is significantly harder/more work I'd rather avoid it if we can, hence the "first pass" approach.

Thoughts?

**Comment by ngld** [comment]
Hm... I'm sorry that I couldn't comment on this earlier.

The list update mechanism was designed at a point where we had much less data (and way fewer mods) and it's really starting to show its age.
My plan regarding this is to move all the searching / filtering logic over to JS since it makes much more sense for it to be there. That removes the whole round-trip for tab switching, searching, etc. It will also allow me to solve a few issues related to the dev tab (it needs direct access to the unfiltered data and a better interface similar to `Repo.query`).

This change will still be beneficial since it's going to reduce the delay between (un)installing mods and updating the list.

**Comment by jg18** [comment]
Cool, thanks for the explanation/context. Yeah I was wondering if the searching/sorting logic should really be in JS rather than Python but assumed it was in Python for a reason. Turns out the reason is just historical. Glad the delta update code is still useful. 🙂

**Comment by ngld** [comment]
All relevant PRs have been merged and I've eliminated a bit of superfluous metadata from being transferred to the JS runtime. Thanks again for your work on this and I'm very sorry it took so long for me to merge it!
