### ISSUE TITLE
Issues with uploading very large packages

### ISSUE THREAD

**Issue by joelywg** [ngld/old-knossos#157]
Not sure if there's just one issue or perhaps a few, but I'll just relate the general issue I had in the hopes of wiser people of devising solutions.

In trying to get Wings of Dawn uploaded, one package was very large, around 3GB after being uploaded. The first attempt at uploading timed out, but I didn't get any notification about it and Knossos just kept increasing the progress bar until I had to ask ngld what was up.

So perhaps Knossos or the server could detect upload timeouts and bring them to the user's attention, and maybe numbers in addition to the progress bar to help tell the user how things are going.

Then on the second try, it uploaded, but the Knossos client sort of lost communication with the server and it didn't progress to uploading the metadata after all packages were uploaded. Restarting Knossos and uploading again worked.

(Also there was one more about downloading the package, but I'm going to put that in a different issue)

**Comment by ngld** [comment]
Fixed by 105cc9826d96bdca6ab13aa0afd35cbef9a37ef6
