### ISSUE TITLE
Innoextract fail

### ISSUE THREAD

**Issue by rsantellan** [ngld/old-knossos#172]
Using innoextract 1.6 gives this error with latest version of GOG file.
`
innoextract setup_freespace_2_1.20_\(32720\).exe 
Warning: Unexpected setup data version: 5.6.2 (unicode)
Warning: Unexpected Auto Boolean value: 19
Warning: Unexpected Auto Boolean value: 20
Warning: Unexpected trailing byte in UTF-16 string.
Warning: Unexpected data while converting from UTF-16LE to UTF-8.
Warning: Unexpected trailing byte in UTF-16 string.
Warning: Unexpected data while converting from UTF-16LE to UTF-8.
Warning: Unexpected data while converting from UTF-16LE to UTF-8.
Stream error while parsing setup headers!
 ├─ detected setup version: 5.6.2 (unicode)
 └─ error reason: basic_ios::clear: iostream error
If you are sure the setup file is not corrupted, consider 
filing a bug report at http://innoextract.constexpr.org/issues
Done with 1 error and 8 warnings
`
I downloaded latest version:
`
innoextract --version
innoextract 1.8
Extracts installers created by Inno Setup 1.2.10 to 6.0.2
`
And I can extract it ok, but the task.py file goes to retrieve the version 1.6 https://fsnebula.org/storage/knossos/innoextract.json
How can I change that to use the system innoexctract ?
I'm using ubuntu 18.04 by the way.
Regards.

**Comment by ngld** [comment]
Using the system innoextract isn't supported since there was never a reason to though you could probably implement that yourself if you wanted to.
However, I've updated the innoextract links to point to 1.8. Let me know if the issue persists.

**Comment by rsantellan** [comment]
@ngld looking at the task file I found that you can use it to install from the decompressed folder. So I did that. I have to remove it to try again ?

**Comment by ngld** [comment]
If you want to check if that fix worked, yes. If you just want to play, you're fine with your current setup.

To test the fix, you have to move the `FS2` folder outside your Knossos library (or delete it but then you'll probably have to reinstall all your mods in addition to the retail files... so I wouldn't recommend that).
If Knossos doesn't see the `FS2` folder on startup, it'll give you the option to install the retail files through a button on the settings screen. However, renaming the folder is not enough. You have to move it outside your library folder or modify the `mod.json` file inside the `FS2` folder.
