### ISSUE TITLE
Using the mod tester functionality causes Explore Tab to not work

### ISSUE THREAD

**Issue by wookieejedi** [ngld/old-knossos#177]
Can confirm with multiple users. If a nebula username is saved to a private mod then that user's explore tab will stop working. If that user is removed from the private mod then explore tab will work again.

**Comment by MitoPL** [comment]
Today @CountBuggula experienced the problem, and for some reason purging the appdata happened to somehow fix it. I'm not sure what that might be caused by, there's been a part of the Knossos log (from before the fix) shared, as follows:
`ERROR:MainThread:web.reportError: JS Error: SyntaxError: Unexpected token e in JSON at position 0
    at JSON.parse (<anonymous>)
    at Function.<anonymous> (qrc:///html/dist/bundle.js:14:4427)
    at qrc:///qtwebchannel/qwebchannel.js:300:26
    at Array.forEach (<anonymous>)
    at invokeSignalCallbacks (qrc:///qtwebchannel/qwebchannel.js:299:25)
    at QObject.signalEmitted (qrc:///qtwebchannel/qwebchannel.js:322:9)
    at QWebChannel.handleSignal (qrc:///qtwebchannel/qwebchannel.js:125:20)
    at Object.QWebChannel.transport.onmessage (qrc:///qtwebchannel/qwebchannel.js:83:25)`

**Comment by wookieejedi** [comment]
Okay, just noting the temporary step-by-step solution here for anyone following along at home:
1) Close Knossos if open. 
2) Go to `%%AppData/Roaming/knossos` and the delete the files in that folder. 
3) Open Knossos and go through the setup again. 
4) Hopefully it's fixed.

**Comment by MitoPL** [comment]
Okay, it isn't fixed, the error comes back with the same error message after restarting Knossos. Also, it was tested on 0.13.3, we'll be trying 0.14 in a moment.

**Comment by wookieejedi** [comment]
Conforming that this is also a bug in 0.14.

**Comment by jg18** [comment]
@wookieejedi @MitoPL  I take it that this is still an issue? Can you be more precise/concrete on what you mean by "stops working"? I'll try to find time to look into this. Thanks.

**Comment by wookieejedi** [comment]
Ah this is actually fixed, I'll close it!
