### ISSUE TITLE
Cannot compile on Arch

### ISSUE THREAD

**Issue by LiamDawe** [ngld/old-knossos#181]
Since the AUR package is broken, I've tried to compile the latest version in the releases tab.

After running the first step it fails, can't figure out what do to from here:

> [pipenv.exceptions.InstallError]: ['Looking in indexes: https://pypi.python.org/simple']
[pipenv.exceptions.InstallError]: ['ERROR: Could not find a version that satisfies the requirement sip==4.19.8 (from -r /tmp/pipenv-5fvmur2d-requirements/pipenv-9cb9nmyz-requirement.txt (line 1)) (from versions: 5.0.0, 5.0.1, 5.1.0, 5.1.1)', 'ERROR: No matching distribution found for sip==4.19.8 (from -r /tmp/pipenv-5fvmur2d-requirements/pipenv-9cb9nmyz-requirement.txt (line 1))']
ERROR: ERROR: Package installation failed...

**Comment by anagram3k** [comment]
The same happen on Ubuntu 20.04 (focal)

> An error occurred while installing sip==4.19.8! Will try again.
> Installing initially–failed dependencies…
> Looking in indexes: https://pypi.python.org/simple00
> 
> ERROR: Could not find a version that satisfies the requirement sip==4.19.8 (from -r /tmp/pipenv-gcglncsk-requirements/pipenv-uvyezsa5-requirement.txt (line 1)) (from versions: 5.0.0, 5.0.1, 5.1.0, 5.1.1, 5.1.2, 5.2.0)
> ERROR: No matching distribution found for sip==4.19.8 (from -r /tmp/pipenv-gcglncsk-requirements/pipenv-uvyezsa5-requirement.txt (line 1))
>

**Comment by ngld** [comment]
The dependencies have been updated. Feel free to re-open if you still have issues installing them.
