### ISSUE TITLE
ninja: build stopped: subcommand failed.

### ISSUE THREAD

**Issue by vlur** [ngld/old-knossos#185]
I am trying to get Knossos running on Void Linux. I did

`python3 -m pip install pyqt5 six requests requests_toolbelt ply semantic_version token_bucket PyQtWebEngine rcc wheel`

to install all the dependencies. Doing `ninja run` gives this output:

```
[1/2] RCC knossos/data/resources.rcc
FAILED: knossos/data/resources.rcc 
/usr/sbin/rcc -binary knossos/data/resources.qrc -o knossos/data/resources.rcc
Usage: rcc [OPTIONS] COMMAND [ARGS]...
Try "rcc --help" for help.

Error: no such option: -b
ninja: build stopped: subcommand failed.
```

I'm not really sure what I'm doing, so it might be a case of user error; Python versions and paths are a somewhat confusing mess to me every time I try compiling something.

I actually have each of the above Python packages installed through Void's package manager (xbps) but it doesn't seem to recognize this fact when I try running `python configure.py` or `python3 configure.py` - it returns an error saying I don't have `semantic_version` installed (and, I assume, a litany of other things required by the configuration script, but I don't know how to resolve any of the errors except by using pip to install the Python packages, as above).

Any advice would be appreciated.

**Comment by ngld** [comment]
Sorry for the late response.
`rcc` is Qt5's *R*esour*c*e *c*ompiler. The `rcc` PyPi package has nothing to do with that.

Apparently, Void Linux's `qt5-host-tools` package includes `rcc-qt5` (which `configure.py` will also detect). Once you've installed that, run `configure.py` again and `ninja run` afterwards.
