### ISSUE TITLE
double-download bug for fs2mod files

### ISSUE THREAD

**Issue by ngld** [ngld/old-knossos#2]
When installing an fs2mod package every file is downloaded and extracted twice.

**Comment by Hellzed** [comment]
Maybe an issue in dependencies handling, since the bug only shows up in fs2mod files that have dependencies. For example, if you install mediavps_3612 alone, file are downloaded and installed only once.

**Comment by ngld** [comment]
The real cause was that I didn't reset `self.urls` in `ModInfo2.read_zip`. Due to the way fs2mod updates are handled right now, `ModInfo2.read_zip` is called twice on the same file during a `FetchTask`. The second call to `ModInfo2.read_zip` read all the URLs again but didn't remove the URLs which were read earlier. The result was that every URL was listed twice and lead to the double downloading and double extracting.
