### ISSUE TITLE
Uninstalled mods not showing up in 0.14.1

### ISSUE THREAD

**Issue by Immortal-Redshirt** [ngld/old-knossos#202]
When clicking on the Explore tab, instead of showing available mods, it only lists mods that are installed.

**Comment by adamlwgriffiths** [comment]
Looks like these two are the same issue:
https://github.com/ngld/knossos/issues/196

The website is 404'ing on the mod list
ERROR:Thread-2:util.get: Failed to load "https://cf.fsnebula.org/storage/repo.json"

And with manually installing mods "not supported", we're all f'ed.
Quality.

**Comment by wookieejedi** [comment]
First, I'd like to point out that this very issue has a hotfix that is getting merged in tonight. 

Second, manually installed mods certainly works if you manually download them from here
[https://fsnebula.org/mods](url)

**Comment by chief1983** [comment]
Is this specific issue in fact a duplicate of #196?  Or is there another cause of the list being empty too now?

**Comment by chief1983** [comment]
This has been fixed in 0.14.3 I believe, the filer can close this if they can confirm they no longer have an issue.

**Comment by Immortal-Redshirt** [comment]
Yep, issue's fixed.
