### ISSUE TITLE
Nebula Signup Fails

### ISSUE THREAD

**Issue by wookieejedi** [ngld/old-knossos#225]
New user making a Nebula account, user receives an email with a confirmation link that does not work.

**Comment by Goober5000** [comment]
What sort of link does he get, and what "doesn't work" about it?  Does he get any error messages?

**Comment by wookieejedi** [comment]
Link is in this form `https://api.fsnebula.org/confirm/%username%/p%character list%`

When clicking on link this message is received:
```
Not Found

The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again. 
```

**Comment by ngld** [comment]
The 404 error indicates that the user either doesn't exist or that the link token (the part after the username) is incorrect. I really should've added a proper error message for that case.
Feel free to DM me on Discord or HLP and I'll activate thair account manually.
