### ISSUE TITLE
Implement an "Upload to pastebin" button in the Log Viewer

### ISSUE THREAD

**Issue by ngld** [ngld/old-knossos#24]
The button should upload the log to https://pastebin.com (they should have an API for this) and put the URL in the user's clipboard. Maybe add BBCode.

**Comment by niffiwan** [comment]
API details here: http://pastebin.com/api

And from here: http://pastebin.com/faq

```
How many pastes can I create?
The short answer is: as many as you like.

There are however some limitations to fight off spammers.

Guests can create up to 10 new pastes per 24 hours.
Free members can create up to 20 new pastes per 24 hours.
PRO members can create up to 250 new pastes per 24 hours.

Further limits are:
Guest can create unlimited 'public' pastes, unlimited 'unlisted' pastes, but can't create 'private' pastes.
Free members can create unlimited 'public' pastes, 25 'unlisted' pastes, 10 'private' pastes.
PRO members can create unlimited 'public' pastes, unlimited 'unlisted' pastes, unlimited 'private' pastes.
```

The free member account could work, 20 pastes in a day _might_ be OK based on current rates of people posting issues on the forum. Or it may be hopelessly small if a lot of people start using the feature, and/or there's lots of people playing that don't sign up to the forum.

A pro account seems to be reasonably cheap at the moment:
http://pastebin.com/pro

30 USD for lifetime account?

**Comment by ngld** [comment]
Log uploads have been implemented using FSNebula.
