### ISSUE TITLE
Mod images in "Installed" tab aren't aligned

### ISSUE THREAD

**Issue by niffiwan** [ngld/old-knossos#27]
Easiest to see with a pic

![image](https://cloud.githubusercontent.com/assets/3313634/23066557/eed1f1a4-f566-11e6-8a03-633c8ac66a57.png)

**Comment by ngld** [comment]
Should I stretch the smaller image or center it?

**Comment by niffiwan** [comment]
Hmm... I'd go with stretch / resize it. Or I guess it could be dealt with at the source; take this action when the mod is uploaded in Nebula and resize the image to common width x height once off then?

**Comment by ngld** [comment]
Nebula only allows a fixed image size but the issue still remains because manually installed mods (BtA in your case) can have varying image sizes.

**Comment by niffiwan** [comment]
oh right :\)  Yeah; then resize in Knossos would be my preference :\)

**Comment by niffiwan** [comment]
pretty sure this is no longer needed given the rework mjn has done to the UI!
