### ISSUE TITLE
"Installation Details" popup does not update when opened in the "Details" page

### ISSUE THREAD

**Issue by asarium** [ngld/old-knossos#70]
When I install a mod from the Details page and then click on the "Installing..." button then the progress bars are frozen and won't update until the dialog is reopened. The progress report works a expected when opened on any of the other pages.

**Comment by ngld** [comment]
The problem is that while the details page copies a reference to the `progress_info` object, that object is replaced each time the progress updates.
One possible solution would be to update that object instead of replacing it but that might break Vue.

**Comment by ngld** [comment]
This should be fixed in 0.7.2, please reopen if it still occurs.
