### ISSUE TITLE
Implement new First Run guide

### ISSUE THREAD

**Issue by MjnMixael** [ngld/old-knossos#73]
Using this basic template, implement the First Run guide to help the setup process be more smooth.

https://imgur.com/a/bA12G

Other notes are to add the option to login at the last step (Suit Up Pilot) and to make sure OpenAL is installed.

**Comment by ngld** [comment]
The new wizard has been implemented as of 2bec6c6387a025e3e741b7c59cb07fb0acb5fd5a.
