### ISSUE TITLE
Starting an install consistency

### ISSUE THREAD

**Issue by MjnMixael** [ngld/old-knossos#77]
When starting an Install, Knossos forces you to the Home tab. However the current order of tasks means that the mod you are installing does not show in the Home tab which means you can't see it's progress unless you go back to Explore.

My preferred way to resolve this is to just keep the user on the Explore tab after an install has begun. Assuming that they can install multiple mods simultaneously, this has the added benefit of keeping them right there to install a few more.

**Comment by ngld** [comment]
I think the reason for switchIng was that back then the progress bar didn't shkw on the explore tab. That's not the case anymore IIRC so we don't need it anymore.
