### ISSUE TITLE
Modifying an installed mod issues

### ISSUE THREAD

**Issue by MjnMixael** [ngld/old-knossos#78]
While testing some things I removed some Option packages from the MediaVPs in the modify tab on a mod that uses MediaVPs as a dependency. Knossos didn't actually delete these packages. However, I cannot launch MediaVPs with these packages anymore, as expected.

However, I cannot reinstall them using the modify tab on MediaVPs in Home or Explore, either.

**Comment by ngld** [comment]
Were the MVPs in dev mode when you tested this?

**Comment by MjnMixael** [comment]
Yes it was.
