### ISSUE TITLE
Scroll needs reset when switching pages

### ISSUE THREAD

**Issue by MjnMixael** [ngld/old-knossos#82]
The best way to see this issue is to start on the Explore tab. Scroll down to find the mod "Warzone". Click Details for Warzone. you'll start at the bottom of the details page.

Whenever we switch tabs or pages, we should bring the user back to the top of the page.

**Comment by MjnMixael** [comment]
Actually, we should take the user to the top of any Details pages. We should return to our previous scrolling position when we go back to Home/Explore.

**Comment by ngld** [comment]
This has been fixed in 0.7.2.
