### ISSUE TITLE
Updater launches Knossos as admin

### ISSUE THREAD

**Issue by Goober5000** [ngld/old-knossos#84]
When starting Knossos for the first time, if you select a directory that doesn't exist, Knossos will not ask if you want to create it.

On a related note, if you start Knossos from the updater, it will launch it under the administrator user, not the current user, which will make Knossos think you are starting it for the first time.

**Comment by ngld** [comment]
The config directory issue should be fixed by the new first run wizard so I've changed the title to reflect the second issue.

**Comment by ngld** [comment]
This should be fixed in the latest versions. Please reopen if this issue still occurs.
